"""Added stars, forks, repo_url

Revision ID: 79b99157bae5
Revises: 170af0cf0285
Create Date: 2019-10-06 20:31:32.634198

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '79b99157bae5'
down_revision = '170af0cf0285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('forked', sa.Integer(), nullable=True))
    op.add_column('repo', sa.Column('repo_url', sa.String(), nullable=True))
    op.add_column('repo', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'stars')
    op.drop_column('repo', 'repo_url')
    op.drop_column('repo', 'forked')
